# Generated by Django 3.2 on 2022-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('news', '0002_newspost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='news_like', to='profiles.UserProfile'),
        ),
    ]
