# Generated by Django 3.2 on 2022-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220402_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_title',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
    ]
