# Generated by Django 3.2 on 2022-03-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merch'},
        ),
        migrations.RemoveField(
            model_name='merch',
            name='limited_number',
        ),
    ]
